### PR TITLE
Updating Singular's Kit integration

### PR DESCRIPTION
**Pull request by eyalsingular**

### CODE REVIEW

**Comment by eyalsingular** [comment]
Hi @samdozor & @angelodipaolo,

I'm Eyal, Singular's SDK engineer.

I see there's an error with the CI for our repo, is there anything we can do to solve it.
Once it's solved, how can i merge our repo fork to yours? 
Should i tag anyone or should it happen automatically with your CI?

Cheers,
Eyal

**Comment by eyalsingular** [comment]
Hi @peterjenkins ,

I'm Eyal, Singular's SDK engineer.

I see there's an error with the CI for our repo, is there anything we can do to solve it.
Once it's solved, how can i merge our repo fork to yours?
Should i tag anyone or should it happen automatically with your CI?

Cheers,
Eyal

**Comment by BrandonStalnaker** [comment]
@eyalsingular We've found Travis CI to be a bit touchy with Kits so we're in the process of updating to use Github Actions.

I pulled your branch and everything seems to be running fine 👍

**Comment by eyalsingular** [comment]
Thank you very much @BrandonStalnaker !!

**Pull request merged**
